=== rohan-ramani/aissemble/foundation/foundation-mda/src/main/resources/aiops-record-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#record",
	"title": "Record",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"dataAccess": {
			"type": "object",
			"properties": {
				"enabled": {
					"type": "boolean"
				}
			}
		},
		"featureRegistration": {
			"type": "object",
			"properties": {
				"enabled": {
					"type": "boolean"
				}
			}
		},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}
						},
						"required": [
							"name"
						]
					},
					"description": {
						"type": "string"
					},
					"column": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"ethicsPolicy": {
						"type": "string"
					},
					"driftPolicy": {
						"type": "string"
					}
				},
				"required": [
					"name", "type"
				]
			}
		},
		"relations": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"package": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"multiplicity": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"column": {
						"type": "string"
					}
				},
				"required": [
					"name","package"
				]
			}
		}
	},
	"required": [
		"name", "package", "fields"
	]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/Mayor.json
{
  "name": "Mayor",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example Mayor record for testing Spark Java Data Relations",
  "fields": [
    {
      "name": "name",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "integerValidation",
      "type": {
        "name": "integerWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "column": "int_v8n"
    }
  ]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/Citizen.json
{
  "name": "Citizen",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example Citizen record for testing Spark Java Data Relations",
  "fields": [
    {
      "name": "name",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "integerValidation",
      "type": {
        "name": "integerWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "column": "int_v8n"
    }
  ]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/RecordWithRequiredValidation.json
{
  "name": "RecordWithRequiredValidation",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example record with a required field that has validation",
  "fields": [
    {
      "name": "integerValidation",
      "type": {
        "name": "integerWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "required": true
    },
    {
      "name": "stringValidation",
      "type": {
        "name": "stringWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "required": true
    },
    {
      "name": "stringSimple",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "required": true
    }
  ]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/Street.json
{
  "name": "Street",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example Street record for testing Spark Java Data Relations",
  "fields": [
    {
      "name": "name",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "county",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "integerValidation",
      "type": {
        "name": "integerWithValidation",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      },
      "column": "int_v8n"
    }
  ]
}
