=== rohan-ramani/aissemble/foundation/foundation-mda/src/main/resources/aiops-record-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"id": "#record",
	"title": "Record",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"name": {
			"type": "string"
		},
		"package": {
			"type": "string"
		},
		"description": {
			"type": "string"
		},
		"dataAccess": {
			"type": "object",
			"properties": {
				"enabled": {
					"type": "boolean"
				}
			}
		},
		"featureRegistration": {
			"type": "object",
			"properties": {
				"enabled": {
					"type": "boolean"
				}
			}
		},
		"fields": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"type": {
						"type": "object",
						"properties": {
							"name": {
								"type": "string"
							},
							"package": {
								"type": "string"
							}
						},
						"required": [
							"name"
						]
					},
					"description": {
						"type": "string"
					},
					"column": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"ethicsPolicy": {
						"type": "string"
					},
					"driftPolicy": {
						"type": "string"
					}
				},
				"required": [
					"name", "type"
				]
			}
		},
		"relations": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"package": {
						"type": "string"
					},
					"documentation": {
						"type": "string"
					},
					"multiplicity": {
						"type": "string"
					},
					"required": {
						"type": "boolean"
					},
					"column": {
						"type": "string"
					}
				},
				"required": [
					"name","package"
				]
			}
		}
	},
	"required": [
		"name", "package", "fields"
	]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/RecordWithNonRequiredValidation.json
{
    "name": "RecordWithNonRequiredValidation",
    "package": "com.boozallen.aiops.mda.pattern.record",
    "description": "Example record with non required field that has validation",
    "fields": [
      {
        "name": "integerValidation",
        "type": {
          "name": "integerWithValidation",
          "package": "com.boozallen.aiops.mda.pattern.dictionary"
        }
      },
      {
        "name": "stringValidation",
        "type": {
          "name": "stringWithValidation",
          "package": "com.boozallen.aiops.mda.pattern.dictionary"
        }
      },
      {
        "name": "stringSimple",
        "type": {
          "name": "string",
          "package": "com.boozallen.aiops.mda.pattern.dictionary"
        }
      }
    ]
  }

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/Address.json
{
  "name": "Address",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Address custom record",
  "fields": [
    {
      "name": "street",
      "required": true,
      "type": {
        "name": "street",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "city",
      "type": {
        "name": "city",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "zipcode",
      "type": {
        "name": "zipcode",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    },
    {
      "name": "state",
      "type": {
        "name": "state",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}

=== rohan-ramani/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/PersonWithOneToOneRelation.json
{
  "name": "PersonWithOneToOneRelation",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Person custom record",
  "relations": [
    {
      "package":"com.boozallen.aiops.mda.pattern.record",
      "multiplicity":"1-1",
      "name":"Address",
      "documentation":"One to One Relation between Person and Address",
      "required": true
    }
  ],
  "fields": [
    {
      "name": "test",
      "type": {
        "name": "customType",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}

=== rohan-ramani/aissemble/foundation/foundation-upgrade/src/test/resources/test-files/v1_11_0/DataAccessDefaultMigration/validation/UndefinedEnabledRecord.json
{
    "name": "UndefinedEnabledRecord",
    "package": "com.boozallen.aissemble.test",
    "description": "A record with data access defined, but dataAccess.enabled undefined",
    "dataAccess": {
        "enabled": true
    },
    "fields": [
        {
            "name": "city",
            "type": {
                "name": "alphaString",
                "package": "com.boozallen.aissemble.test.dictionary"
            }
        },
        {
            "name": "state",
            "type": {
                "name": "stateCode",
                "package": "com.boozallen.aissemble.test.dictionary"
            }
        }
    ]
}

=== rohan-ramani/aissemble/test/test-mda-models/aissemble-test-data-delivery-pyspark-model/src/aissemble_test_data_delivery_pyspark_model/resources/records/PersonWithMToOneRelation.json
{
  "name": "PersonWithMToOneRelation",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Person custom record",
  "fields": [
    {
      "name": "customField",
      "type": {
        "name": "customType",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ],
  "relations": [
    {
      "package":"com.boozallen.aiops.mda.pattern.record",
      "multiplicity":"m-1",
      "name":"Address",
      "documentation":"Many to One Relation between Person and Address"
    }
  ]
}

=== rohan-ramani/aissemble/foundation/foundation-upgrade/src/test/resources/test-files/v1_11_0/DataAccessDefaultMigration/validation/UndefinedDataAccessRecord.json
{
  "name": "UndefinedDataAccessRecord",
  "package": "com.boozallen.aissemble.test",
  "description": "A record with data access undefined",
  "fields": [
    {
      "name": "city",
      "type": {
        "name": "alphaString",
        "package": "com.boozallen.aissemble.test.dictionary"
      }
    },
    {
      "name": "state",
      "type": {
        "name": "stateCode",
        "package": "com.boozallen.aissemble.test.dictionary"
      }
    }
  ],
  "dataAccess": {
    "enabled": true
  }
}

=== rohan-ramani/aissemble/foundation/foundation-upgrade/src/test/resources/test-files/v1_11_0/DataAccessDefaultMigration/migration/ExplicitRecord.json
{
  "name": "ExplicitRecord",
  "package": "com.boozallen.aissemble.test",
  "description": "A record with data access explicitly set",
  "dataAccess": {
    "enabled": false
  },
  "fields": [
    {
      "name": "city",
      "type": {
        "name": "alphaString",
        "package": "com.boozallen.aissemble.test.dictionary"
      }
    },
    {
      "name": "state",
      "type": {
        "name": "stateCode",
        "package": "com.boozallen.aissemble.test.dictionary"
      }
    }
  ]
}

=== rohan-ramani/aissemble/test/test-mda-models/test-data-delivery-spark-model/src/main/resources/records/State.json
{
  "name": "State",
  "package": "com.boozallen.aiops.mda.pattern.record",
  "description": "Example State record for testing Spark Java Data Relations",
  "fields": [
    {
      "name": "name",
      "type": {
        "name": "string",
        "package": "com.boozallen.aiops.mda.pattern.dictionary"
      }
    }
  ]
}
